apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-users
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: '10.43.36.55'
    path: '/jenkins-users'
