apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-state
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  nfs:
    server: '10.43.36.55'
    path: '/jenkins-state'
