kind: Service
apiVersion: v1
metadata:
  name: jenkins-stable
spec:
  ports:
    - name: 'http'
      port: 80
      targetPort: 8080
    - name: 'slave'
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
    release: stable
