kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: host-based-ingress
  annotations:
    allow.http: 'false'
spec:
  tls:
    - secretName: 'any-actano-de'
  rules:
  - host: jenkins.actano.de
    http:
      paths:
      - backend: 
          serviceName: jenkins-stable
          servicePort: 80
