kind: Service
apiVersion: v1
metadata:
  name: selenium-hub-ci
  labels:
    app: selenium-hub
    environment: CI
spec:
  ports:
    - port: 4444
      targetPort: 4444
  selector:
    app: selenium-hub
    environment: CI
